[Interface]
Address = 10.100.0.1/24
ListenPort = 51820
PrivateKey = CENTRAL_PRIVATE_KEY

# MSK peer
[Peer]
PublicKey = MSK_PUBLIC_KEY
AllowedIPs = 10.100.0.2/32

# NSK peer
[Peer]
PublicKey = NSK_PUBLIC_KEY
AllowedIPs = 10.100.0.3/32

# VVO peer
[Peer]
PublicKey = VVO_PUBLIC_KEY
AllowedIPs = 10.100.0.4/32
